/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "D:\\F盘\\桌面\\vue项目实战\\前端所有笔记\\vuepress_study\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "D:\\F盘\\桌面\\vue项目实战\\前端所有笔记\\vuepress_study\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "D:\\F盘\\桌面\\vue项目实战\\前端所有笔记\\vuepress_study\\node_modules\\@vuepress\\plugin-medium-zoom\\clientRootMixin.js"
import m3 from "D:\\F盘\\桌面\\vue项目实战\\前端所有笔记\\vuepress_study\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m4 from "D:\\F盘\\桌面\\vue项目实战\\前端所有笔记\\vuepress_study\\node_modules\\vuepress-plugin-smooth-scroll\\lib\\clientRootMixin.js"
import m5 from "D:\\F盘\\桌面\\vue项目实战\\前端所有笔记\\vuepress_study\\node_modules\\vuepress-plugin-nuggets-style-copy\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3,
  m4,
  m5
]