/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\F盘\\桌面\\vue项目实战\\前端所有笔记\\vuepress_study\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-418dc0c6",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-418dc0c6").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0f68e1a2",
    path: "/html/css2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f68e1a2").then(next)
    },
  },
  {
    name: "v-1393ca20",
    path: "/html/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1393ca20").then(next)
    },
  },
  {
    name: "v-66a57ee2",
    path: "/html/h5c3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66a57ee2").then(next)
    },
  },
  {
    name: "v-5a38a422",
    path: "/html/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a38a422").then(next)
    },
  },
  {
    name: "v-15ddb0b2",
    path: "/html/details.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15ddb0b2").then(next)
    },
  },
  {
    name: "v-83f098ee",
    path: "/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-83f098ee").then(next)
    },
  },
  {
    path: "/js/index.html",
    redirect: "/js/"
  },
  {
    name: "v-07eeab42",
    path: "/html/mobile.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07eeab42").then(next)
    },
  },
  {
    name: "v-7ce05aa2",
    path: "/js/j1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ce05aa2").then(next)
    },
  },
  {
    name: "v-4f1ec4fc",
    path: "/js/j2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f1ec4fc").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]