/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "MC猴的博客",
  "description": "你在凝望深渊的时候，深渊也在凝望你！！！",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "MC猴"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "html,css,vue,vue项目,MC猴的网站"
      }
    ],
    [
      "script",
      {},
      "var _hmt = _hmt || []\n      ;(function () {\n        var hm = document.createElement('script')\n        hm.src = 'https://hm.baidu.com/hm.js?c1461b58ad9f5b7d36d29eab68e45f38'\n        var s = document.getElementsByTagName('script')[0]\n        s.parentNode.insertBefore(hm, s)\n      })()"
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "现在不努力，什么时候努力",
        "tagline": "go to study",
        "actionText": "快速上手 →",
        "actionLink": "/html/html",
        "bgImage": "/img/bg.png",
        "bgImageStyle": {
          "height": "400px"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-418dc0c6",
      "path": "/",
      "lastUpdated": "2022年1月6日星期四晚上10点48分",
      "lastUpdatedTimestamp": 1641480499000
    },
    {
      "title": "CSS基础二",
      "frontmatter": {
        "title": "CSS基础二",
        "sidebarDepth": 0,
        "date": "2022-01-05T00:00:00.000Z",
        "categories": [
          "H5C3"
        ],
        "tags": [
          "css"
        ]
      },
      "regularPath": "/html/css2.html",
      "relativePath": "html/css2.md",
      "key": "v-0f68e1a2",
      "path": "/html/css2.html",
      "headers": [
        {
          "level": 3,
          "title": "markdown正文",
          "slug": "markdown正文"
        },
        {
          "level": 2,
          "title": "1. 盒子边框(border)",
          "slug": "_1-盒子边框-border"
        },
        {
          "level": 2,
          "title": "2. 内边距(padding)",
          "slug": "_2-内边距-padding"
        },
        {
          "level": 2,
          "title": "3. 外边距（margin）",
          "slug": "_3-外边距-margin"
        },
        {
          "level": 2,
          "title": "4.外边距合并",
          "slug": "_4-外边距合并"
        },
        {
          "level": 2,
          "title": "5. CSS3 新增",
          "slug": "_5-css3-新增"
        },
        {
          "level": 2,
          "title": "CSS布局的三种机制",
          "slug": "css布局的三种机制"
        },
        {
          "level": 2,
          "title": "清除浮动",
          "slug": "清除浮动"
        },
        {
          "level": 2,
          "title": "CSS属性书写顺序",
          "slug": "css属性书写顺序"
        },
        {
          "level": 2,
          "title": "定位模式(position)",
          "slug": "定位模式-position"
        },
        {
          "level": 2,
          "title": "定位(position)的扩展",
          "slug": "定位-position-的扩展"
        },
        {
          "level": 2,
          "title": "元素的显示与隐藏",
          "slug": "元素的显示与隐藏"
        },
        {
          "level": 2,
          "title": "CSS用户界面样式",
          "slug": "css用户界面样式"
        },
        {
          "level": 2,
          "title": "vertical-align 垂直对齐",
          "slug": "vertical-align-垂直对齐"
        },
        {
          "level": 2,
          "title": "溢出的文字省略号显示",
          "slug": "溢出的文字省略号显示"
        },
        {
          "level": 2,
          "title": "CSS 三角形",
          "slug": "css-三角形"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>本文主要包括css的基本部分二，选取至pink老师</p>\n</div>",
      "lastUpdated": "2022年1月6日星期四晚上10点48分",
      "lastUpdatedTimestamp": 1641480499000
    },
    {
      "title": "CSS基础一",
      "frontmatter": {
        "title": "CSS基础一",
        "sidebarDepth": 0,
        "date": "2022-01-05T00:00:00.000Z",
        "categories": [
          "H5C3"
        ],
        "tags": [
          "css"
        ]
      },
      "regularPath": "/html/css.html",
      "relativePath": "html/css.md",
      "key": "v-1393ca20",
      "path": "/html/css.html",
      "headers": [
        {
          "level": 3,
          "title": "markdown正文",
          "slug": "markdown正文"
        },
        {
          "level": 2,
          "title": "1. CSS基础选择器",
          "slug": "_1-css基础选择器"
        },
        {
          "level": 3,
          "title": "① 标签选择器",
          "slug": "_1-标签选择器"
        },
        {
          "level": 3,
          "title": "② 类选择器",
          "slug": "_2-类选择器"
        },
        {
          "level": 3,
          "title": "③ id选择器",
          "slug": "_3-id选择器"
        },
        {
          "level": 3,
          "title": "④ 通配符选择器",
          "slug": "_4-通配符选择器"
        },
        {
          "level": 3,
          "title": "⑤基础选择器总结",
          "slug": "_5基础选择器总结"
        },
        {
          "level": 2,
          "title": "2.CSS复合选择器",
          "slug": "_2-css复合选择器"
        },
        {
          "level": 3,
          "title": "① 后代选择器（包含选择器）",
          "slug": "_1-后代选择器-包含选择器"
        },
        {
          "level": 3,
          "title": "② 子元素选择器",
          "slug": "_2-子元素选择器"
        },
        {
          "level": 3,
          "title": "③ 交集选择器/并集选择器",
          "slug": "_3-交集选择器-并集选择器"
        },
        {
          "level": 3,
          "title": "④ 链接伪类选择器",
          "slug": "_4-链接伪类选择器"
        },
        {
          "level": 3,
          "title": "⑤ 复合选择器总结",
          "slug": "_5-复合选择器总结"
        },
        {
          "level": 2,
          "title": "font字体",
          "slug": "font字体"
        },
        {
          "level": 2,
          "title": "CSS外观属性",
          "slug": "css外观属性"
        },
        {
          "level": 2,
          "title": "标签显示模式转换 display",
          "slug": "标签显示模式转换-display"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>本文主要包括css的基本部分一，选取至pink老师</p>\n</div>",
      "lastUpdated": "2022年1月6日星期四晚上10点48分",
      "lastUpdatedTimestamp": 1641480499000
    },
    {
      "title": "利用视口单位适配页面",
      "frontmatter": {
        "title": "利用视口单位适配页面",
        "sidebarDepth": 0,
        "date": "2022-01-07T00:00:00.000Z",
        "categories": [
          "H5C3"
        ],
        "tags": [
          "视口适配页面"
        ]
      },
      "regularPath": "/html/css3.html",
      "relativePath": "html/css3.md",
      "key": "v-426fc7fc",
      "path": "/html/css3.html",
      "headers": [
        {
          "level": 3,
          "title": "markdown正文",
          "slug": "markdown正文"
        },
        {
          "level": 2,
          "title": "利用视口单位适配页面",
          "slug": "利用视口单位适配页面"
        },
        {
          "level": 3,
          "title": "做法一：仅使用vw作为CSS单位",
          "slug": "做法一-仅使用vw作为css单位"
        },
        {
          "level": 3,
          "title": "做法二：搭配vw和rem，布局更优化",
          "slug": "做法二-搭配vw和rem-布局更优化"
        },
        {
          "level": 3,
          "title": "小结",
          "slug": "小结"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>CSS - 利用视口单位适配页面</p>\n</div>"
    },
    {
      "title": "HTML5 + CSS3 新特性",
      "frontmatter": {
        "title": "HTML5 + CSS3 新特性",
        "sidebarDepth": 0,
        "date": "2022-01-05T00:00:00.000Z",
        "categories": [
          "H5C3"
        ],
        "tags": [
          "h5c3新特性"
        ]
      },
      "regularPath": "/html/h5c3.html",
      "relativePath": "html/h5c3.md",
      "key": "v-66a57ee2",
      "path": "/html/h5c3.html",
      "headers": [
        {
          "level": 3,
          "title": "markdown正文",
          "slug": "markdown正文"
        },
        {
          "level": 2,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 2,
          "title": "HTML5新增标签",
          "slug": "html5新增标签"
        },
        {
          "level": 3,
          "title": "语义化标签",
          "slug": "语义化标签"
        },
        {
          "level": 3,
          "title": "音视频",
          "slug": "音视频"
        },
        {
          "level": 3,
          "title": "input标签",
          "slug": "input标签"
        },
        {
          "level": 2,
          "title": "选择器",
          "slug": "选择器"
        },
        {
          "level": 3,
          "title": "结构伪类选择器",
          "slug": "结构伪类选择器"
        },
        {
          "level": 2,
          "title": "2D转换",
          "slug": "_2d转换"
        },
        {
          "level": 2,
          "title": "CSS 过渡transition",
          "slug": "css-过渡transition"
        },
        {
          "level": 2,
          "title": "动画(animation)",
          "slug": "动画-animation"
        },
        {
          "level": 3,
          "title": "动画属性",
          "slug": "动画属性"
        },
        {
          "level": 2,
          "title": "3D转换",
          "slug": "_3d转换"
        },
        {
          "level": 3,
          "title": "3D 移动translate",
          "slug": "_3d-移动translate"
        },
        {
          "level": 3,
          "title": "透视perspective",
          "slug": "透视perspective"
        },
        {
          "level": 3,
          "title": "3D 旋转rotate(X,Y,Z)",
          "slug": "_3d-旋转rotate-x-y-z"
        },
        {
          "level": 3,
          "title": "3D呈现transform-style",
          "slug": "_3d呈现transform-style"
        },
        {
          "level": 2,
          "title": "浏览器私有前缀",
          "slug": "浏览器私有前缀"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>本文主要介绍h5c3的新特性，选取至pink老师</p>\n</div>",
      "lastUpdated": "2022年1月6日星期四晚上10点48分",
      "lastUpdatedTimestamp": 1641480499000
    },
    {
      "title": "查漏补缺",
      "frontmatter": {
        "title": "查漏补缺",
        "sidebarDepth": 0,
        "date": "2022-01-07T00:00:00.000Z",
        "categories": [
          "H5C3"
        ],
        "tags": [
          "CSS-查漏补缺"
        ]
      },
      "regularPath": "/html/css4.html",
      "relativePath": "html/css4.md",
      "key": "v-a3b1533c",
      "path": "/html/css4.html",
      "headers": [
        {
          "level": 3,
          "title": "markdown正文",
          "slug": "markdown正文"
        },
        {
          "level": 2,
          "title": "Ⅰ-css3 pointer-events",
          "slug": "i-css3-pointer-events"
        },
        {
          "level": 2,
          "title": "Ⅰ-图片不拉伸属性  object-fit",
          "slug": "i-图片不拉伸属性-object-fit"
        },
        {
          "level": 2,
          "title": "Ⅱ-css鼠标点击的五种状态",
          "slug": "ii-css鼠标点击的五种状态"
        },
        {
          "level": 2,
          "title": "Ⅲ-阴影效果",
          "slug": "iii-阴影效果"
        },
        {
          "level": 2,
          "title": "Ⅳ-实现a标签禁用",
          "slug": "iv-实现a标签禁用"
        },
        {
          "level": 2,
          "title": "Ⅴ-实现父元素半透明，子元素不透明",
          "slug": "v-实现父元素半透明-子元素不透明"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>CSS - 查漏补缺</p>\n</div>"
    },
    {
      "title": "HTML中的一些细节",
      "frontmatter": {
        "title": "HTML中的一些细节",
        "sidebarDepth": 0,
        "date": "2022-01-05T00:00:00.000Z",
        "categories": [
          "H5C3"
        ],
        "tags": [
          "html细节"
        ]
      },
      "regularPath": "/html/details.html",
      "relativePath": "html/details.md",
      "key": "v-15ddb0b2",
      "path": "/html/details.html",
      "headers": [
        {
          "level": 3,
          "title": "markdown正文",
          "slug": "markdown正文"
        },
        {
          "level": 3,
          "title": "1、fetch请求",
          "slug": "_1、fetch请求"
        },
        {
          "level": 3,
          "title": "2、xhr请求",
          "slug": "_2、xhr请求"
        },
        {
          "level": 3,
          "title": "3、未跨域报错",
          "slug": "_3、未跨域报错"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>本文主要包括HTML中的一些细节</p>\n</div>",
      "lastUpdated": "2022年1月6日星期四晚上10点48分",
      "lastUpdatedTimestamp": 1641480499000
    },
    {
      "title": "HTML基础篇",
      "frontmatter": {
        "title": "HTML基础篇",
        "sidebarDepth": 0,
        "date": "2022-01-05T00:00:00.000Z",
        "categories": [
          "H5C3"
        ],
        "tags": [
          "html"
        ]
      },
      "regularPath": "/html/html.html",
      "relativePath": "html/html.md",
      "key": "v-5a38a422",
      "path": "/html/html.html",
      "headers": [
        {
          "level": 3,
          "title": "markdown正文",
          "slug": "markdown正文"
        },
        {
          "level": 2,
          "title": "1.1 前提知识",
          "slug": "_1-1-前提知识"
        },
        {
          "level": 2,
          "title": "1.2 Web标准",
          "slug": "_1-2-web标准"
        },
        {
          "level": 2,
          "title": "2.1 HTML初识",
          "slug": "_2-1-html初识"
        },
        {
          "level": 2,
          "title": "2.2 文档类型声明标签",
          "slug": "_2-2-文档类型声明标签"
        },
        {
          "level": 2,
          "title": "2.3 lang语言种类",
          "slug": "_2-3-lang语言种类"
        },
        {
          "level": 3,
          "title": "2.4 字符集",
          "slug": "_2-4-字符集"
        },
        {
          "level": 2,
          "title": "3.1、标题标签",
          "slug": "_3-1、标题标签"
        },
        {
          "level": 2,
          "title": "3.2、段落标签",
          "slug": "_3-2、段落标签"
        },
        {
          "level": 2,
          "title": "3.3、换行标签/水平线标签",
          "slug": "_3-3、换行标签-水平线标签"
        },
        {
          "level": 2,
          "title": "3.4、文本格式化标签",
          "slug": "_3-4、文本格式化标签"
        },
        {
          "level": 2,
          "title": "3.5 图像标签",
          "slug": "_3-5-图像标签"
        },
        {
          "level": 2,
          "title": "3.6 链接标签(重点)",
          "slug": "_3-6-链接标签-重点"
        },
        {
          "level": 2,
          "title": "3.7 特殊字符",
          "slug": "_3-7-特殊字符"
        },
        {
          "level": 2,
          "title": "4.1 表格标签",
          "slug": "_4-1-表格标签"
        },
        {
          "level": 2,
          "title": "4.2 表格属性",
          "slug": "_4-2-表格属性"
        },
        {
          "level": 2,
          "title": "4.3 列表",
          "slug": "_4-3-列表"
        },
        {
          "level": 2,
          "title": "form表单域",
          "slug": "form表单域"
        },
        {
          "level": 2,
          "title": "input 控件",
          "slug": "input-控件"
        },
        {
          "level": 2,
          "title": "label标签",
          "slug": "label标签"
        },
        {
          "level": 2,
          "title": "textarea控件(文本域)",
          "slug": "textarea控件-文本域"
        },
        {
          "level": 2,
          "title": "select下拉列表",
          "slug": "select下拉列表"
        },
        {
          "level": 2,
          "title": "label的作用是什么？是怎么用的？",
          "slug": "label的作用是什么-是怎么用的"
        },
        {
          "level": 2,
          "title": "什么是 HTML5 的基本构件（building block）？",
          "slug": "什么是-html5-的基本构件-building-block"
        },
        {
          "level": 2,
          "title": "link和@import的区别",
          "slug": "link和-import的区别"
        },
        {
          "level": 2,
          "title": "src与href的区别",
          "slug": "src与href的区别"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>本文主要包括html的基本部分，选取至pink老师</p>\n</div>",
      "lastUpdated": "2022年1月6日星期四晚上10点48分",
      "lastUpdatedTimestamp": 1641480499000
    },
    {
      "title": "移动端布局",
      "frontmatter": {
        "title": "移动端布局",
        "sidebarDepth": 0,
        "date": "2022-01-05T00:00:00.000Z",
        "categories": [
          "移动端"
        ],
        "tags": [
          "h5"
        ]
      },
      "regularPath": "/html/mobile.html",
      "relativePath": "html/mobile.md",
      "key": "v-07eeab42",
      "path": "/html/mobile.html",
      "headers": [
        {
          "level": 3,
          "title": "markdown正文",
          "slug": "markdown正文"
        },
        {
          "level": 2,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 2,
          "title": "视口",
          "slug": "视口"
        },
        {
          "level": 2,
          "title": "二倍图",
          "slug": "二倍图"
        },
        {
          "level": 2,
          "title": "移动端技术解决方案",
          "slug": "移动端技术解决方案"
        },
        {
          "level": 2,
          "title": "移动端常见布局 - 流失布局",
          "slug": "移动端常见布局-流失布局"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "flex 布局原理 ✍",
          "slug": "flex-布局原理-✍"
        },
        {
          "level": 2,
          "title": "flex 布局父项常见属性",
          "slug": "flex-布局父项常见属性"
        },
        {
          "level": 3,
          "title": "justify-content",
          "slug": "justify-content"
        },
        {
          "level": 3,
          "title": "align-content",
          "slug": "align-content"
        },
        {
          "level": 2,
          "title": "flex 布局子项常见属性",
          "slug": "flex-布局子项常见属性"
        },
        {
          "level": 2,
          "title": "背景线性渐变",
          "slug": "背景线性渐变"
        },
        {
          "level": 2,
          "title": "rem 基础",
          "slug": "rem-基础"
        },
        {
          "level": 2,
          "title": "媒体查询",
          "slug": "媒体查询"
        },
        {
          "level": 3,
          "title": "语法规范",
          "slug": "语法规范"
        },
        {
          "level": 2,
          "title": "Less 基础",
          "slug": "less-基础"
        },
        {
          "level": 3,
          "title": "Less 使用",
          "slug": "less-使用"
        },
        {
          "level": 2,
          "title": "响应式开发",
          "slug": "响应式开发"
        },
        {
          "level": 2,
          "title": "Bootstrap前端开发框",
          "slug": "bootstrap前端开发框"
        },
        {
          "level": 3,
          "title": "Bootstrap 简介",
          "slug": "bootstrap-简介"
        },
        {
          "level": 2,
          "title": "Bootstrap栅格系统",
          "slug": "bootstrap栅格系统"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>本文主要介绍H5网页移动端布局，包含流失布局、Flex(弹性盒) 布局、等...</p>\n</div>",
      "lastUpdated": "2022年1月6日星期四晚上10点48分",
      "lastUpdatedTimestamp": 1641480499000
    },
    {
      "title": "11",
      "frontmatter": {},
      "regularPath": "/js/",
      "relativePath": "js/README.md",
      "key": "v-83f098ee",
      "path": "/js/",
      "lastUpdated": "2022年1月5日星期三下午5点28分",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "我是js",
      "frontmatter": {},
      "regularPath": "/js/j1.html",
      "relativePath": "js/j1.md",
      "key": "v-7ce05aa2",
      "path": "/js/j1.html",
      "headers": [
        {
          "level": 2,
          "title": "es6",
          "slug": "es6"
        }
      ],
      "lastUpdated": "2022年1月5日星期三下午5点28分",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "11",
      "frontmatter": {},
      "regularPath": "/js/j2.html",
      "relativePath": "js/j2.md",
      "key": "v-4f1ec4fc",
      "path": "/js/j2.html",
      "headers": [
        {
          "level": 2,
          "title": "66",
          "slug": "_66"
        }
      ],
      "lastUpdated": "2022年1月5日星期三下午5点28分",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "css Tags"
      },
      "regularPath": "/tag/css/",
      "key": "v-323b9794",
      "path": "/tag/css/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "视口适配页面 Tags"
      },
      "regularPath": "/tag/%E8%A7%86%E5%8F%A3%E9%80%82%E9%85%8D%E9%A1%B5%E9%9D%A2/",
      "key": "v-0dafe5c8",
      "path": "/tag/视口适配页面/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "h5c3新特性 Tags"
      },
      "regularPath": "/tag/h5c3%E6%96%B0%E7%89%B9%E6%80%A7/",
      "key": "v-64b9d830",
      "path": "/tag/h5c3新特性/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CSS-查漏补缺 Tags"
      },
      "regularPath": "/tag/CSS-%E6%9F%A5%E6%BC%8F%E8%A1%A5%E7%BC%BA/",
      "key": "v-6514691c",
      "path": "/tag/CSS-查漏补缺/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "html细节 Tags"
      },
      "regularPath": "/tag/html%E7%BB%86%E8%8A%82/",
      "key": "v-55bf7874",
      "path": "/tag/html细节/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "html Tags"
      },
      "regularPath": "/tag/html/",
      "key": "v-14a9a50c",
      "path": "/tag/html/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "h5 Tags"
      },
      "regularPath": "/tag/h5/",
      "key": "v-e8d88bd0",
      "path": "/tag/h5/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "H5C3 Categories"
      },
      "regularPath": "/categories/H5C3/",
      "key": "v-6106cb74",
      "path": "/categories/H5C3/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "移动端 Categories"
      },
      "regularPath": "/categories/%E7%A7%BB%E5%8A%A8%E7%AB%AF/",
      "key": "v-5f0beb54",
      "path": "/categories/移动端/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "logo": "/img/logo.jpg",
    "author": "MC猴",
    "authorAvatar": "/img/logo.jpg",
    "lastUpdated": "最近更新时间",
    "nav": [
      {
        "text": "HTML",
        "link": "/html/html"
      },
      {
        "text": "JS",
        "link": "/js/"
      },
      {
        "text": "AJAX",
        "link": "/ajax/"
      },
      {
        "text": "VUE",
        "link": "/vue/"
      },
      {
        "text": "VUE项目",
        "items": [
          {
            "text": "网抑云音乐PC",
            "link": "http://music.ychzx.top"
          },
          {
            "text": "前台购物项目",
            "link": "http://shop.ychzx.top"
          },
          {
            "text": "后台电商管理项目",
            "link": "http://admin.ychzx.top"
          }
        ]
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ],
    "sidebar": {
      "/html/": [
        "html",
        "css",
        "css2",
        "h5c3",
        "mobile",
        "details",
        "css3",
        "css4"
      ],
      "/js/": [
        "j1",
        "j2"
      ]
    },
    "subSidebar": "auto",
    "noFoundPageByTencent": false,
    "blogConfig": {
      "socialLinks": [
        {
          "icon": "reco-github",
          "link": "https://github.com/jxmchou"
        },
        {
          "icon": "reco-mayun",
          "link": "https://gitee.com/mchou"
        },
        {
          "icon": "reco-csdn",
          "link": "https://blog.csdn.net/jxmchou/article/details/121063363?spm=1001.2014.3001.5501"
        },
        {
          "icon": "reco-juejin",
          "link": "https://juejin.cn/"
        },
        {
          "icon": "reco-other",
          "link": "http://music.ychzx.top/",
          "title": "网抑云音乐PC"
        }
      ]
    },
    "record": "ICP 备案文案",
    "recordLink": "ICP 备案指向链接",
    "cyberSecurityRecord": "公安部备案文案",
    "cyberSecurityLink": "公安部备案指向链接",
    "startYear": "2022",
    "search": true,
    "searchMaxSuggestions": 10
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}