/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "MC猴的网站",
  "description": "MC猴的网站,MC猴的博客，MC猴的笔记",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "MC猴"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "html,css,vue,vue项目,MC猴的网站"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "MC猴的网站",
        "tagline": "go to study",
        "actionText": "快速上手 →",
        "actionLink": "/html/html",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-418dc0c6",
      "path": "/",
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "3.CSS基础二",
      "frontmatter": {
        "title": "3.CSS基础二",
        "sidebarDepth": 0
      },
      "regularPath": "/html/css2.html",
      "relativePath": "html/css2.md",
      "key": "v-0f68e1a2",
      "path": "/html/css2.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 盒子边框(border)",
          "slug": "_1-盒子边框-border"
        },
        {
          "level": 2,
          "title": "2. 内边距(padding)",
          "slug": "_2-内边距-padding"
        },
        {
          "level": 2,
          "title": "3. 外边距（margin）",
          "slug": "_3-外边距-margin"
        },
        {
          "level": 2,
          "title": "4.外边距合并",
          "slug": "_4-外边距合并"
        },
        {
          "level": 2,
          "title": "5. CSS3 新增",
          "slug": "_5-css3-新增"
        },
        {
          "level": 2,
          "title": "CSS布局的三种机制",
          "slug": "css布局的三种机制"
        },
        {
          "level": 2,
          "title": "清除浮动",
          "slug": "清除浮动"
        },
        {
          "level": 2,
          "title": "CSS属性书写顺序",
          "slug": "css属性书写顺序"
        },
        {
          "level": 2,
          "title": "定位模式(position)",
          "slug": "定位模式-position"
        },
        {
          "level": 2,
          "title": "定位(position)的扩展",
          "slug": "定位-position-的扩展"
        },
        {
          "level": 2,
          "title": "元素的显示与隐藏",
          "slug": "元素的显示与隐藏"
        },
        {
          "level": 2,
          "title": "CSS用户界面样式",
          "slug": "css用户界面样式"
        },
        {
          "level": 2,
          "title": "vertical-align 垂直对齐",
          "slug": "vertical-align-垂直对齐"
        },
        {
          "level": 2,
          "title": "溢出的文字省略号显示",
          "slug": "溢出的文字省略号显示"
        },
        {
          "level": 2,
          "title": "CSS 三角形",
          "slug": "css-三角形"
        }
      ],
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "2.CSS基础一",
      "frontmatter": {
        "title": "2.CSS基础一",
        "sidebarDepth": 0
      },
      "regularPath": "/html/css.html",
      "relativePath": "html/css.md",
      "key": "v-1393ca20",
      "path": "/html/css.html",
      "headers": [
        {
          "level": 2,
          "title": "1. CSS基础选择器",
          "slug": "_1-css基础选择器"
        },
        {
          "level": 3,
          "title": "① 标签选择器",
          "slug": "_1-标签选择器"
        },
        {
          "level": 3,
          "title": "② 类选择器",
          "slug": "_2-类选择器"
        },
        {
          "level": 3,
          "title": "③ id选择器",
          "slug": "_3-id选择器"
        },
        {
          "level": 3,
          "title": "④ 通配符选择器",
          "slug": "_4-通配符选择器"
        },
        {
          "level": 3,
          "title": "⑤基础选择器总结",
          "slug": "_5基础选择器总结"
        },
        {
          "level": 2,
          "title": "2.CSS复合选择器",
          "slug": "_2-css复合选择器"
        },
        {
          "level": 3,
          "title": "① 后代选择器（包含选择器）",
          "slug": "_1-后代选择器-包含选择器"
        },
        {
          "level": 3,
          "title": "② 子元素选择器",
          "slug": "_2-子元素选择器"
        },
        {
          "level": 3,
          "title": "③ 交集选择器/并集选择器",
          "slug": "_3-交集选择器-并集选择器"
        },
        {
          "level": 3,
          "title": "④ 链接伪类选择器",
          "slug": "_4-链接伪类选择器"
        },
        {
          "level": 3,
          "title": "⑤ 复合选择器总结",
          "slug": "_5-复合选择器总结"
        },
        {
          "level": 2,
          "title": "font字体",
          "slug": "font字体"
        },
        {
          "level": 2,
          "title": "CSS外观属性",
          "slug": "css外观属性"
        },
        {
          "level": 2,
          "title": "标签显示模式转换 display",
          "slug": "标签显示模式转换-display"
        }
      ],
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "4.HTML5 + CSS3 新特性",
      "frontmatter": {
        "title": "4.HTML5 + CSS3 新特性",
        "sidebarDepth": 0
      },
      "regularPath": "/html/h5c3.html",
      "relativePath": "html/h5c3.md",
      "key": "v-66a57ee2",
      "path": "/html/h5c3.html",
      "headers": [
        {
          "level": 2,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 2,
          "title": "HTML5新增标签",
          "slug": "html5新增标签"
        },
        {
          "level": 3,
          "title": "语义化标签",
          "slug": "语义化标签"
        },
        {
          "level": 3,
          "title": "音视频",
          "slug": "音视频"
        },
        {
          "level": 3,
          "title": "input标签",
          "slug": "input标签"
        },
        {
          "level": 2,
          "title": "选择器",
          "slug": "选择器"
        },
        {
          "level": 3,
          "title": "结构伪类选择器",
          "slug": "结构伪类选择器"
        },
        {
          "level": 2,
          "title": "2D转换",
          "slug": "_2d转换"
        },
        {
          "level": 2,
          "title": "CSS 过渡transition",
          "slug": "css-过渡transition"
        },
        {
          "level": 2,
          "title": "动画(animation)",
          "slug": "动画-animation"
        },
        {
          "level": 3,
          "title": "动画属性",
          "slug": "动画属性"
        },
        {
          "level": 2,
          "title": "3D转换",
          "slug": "_3d转换"
        },
        {
          "level": 3,
          "title": "3D 移动translate",
          "slug": "_3d-移动translate"
        },
        {
          "level": 3,
          "title": "透视perspective",
          "slug": "透视perspective"
        },
        {
          "level": 3,
          "title": "3D 旋转rotate(X,Y,Z)",
          "slug": "_3d-旋转rotate-x-y-z"
        },
        {
          "level": 3,
          "title": "3D呈现transform-style",
          "slug": "_3d呈现transform-style"
        },
        {
          "level": 2,
          "title": "浏览器私有前缀",
          "slug": "浏览器私有前缀"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "1.HTML基础篇",
      "frontmatter": {
        "title": "1.HTML基础篇",
        "sidebarDepth": 0
      },
      "regularPath": "/html/html.html",
      "relativePath": "html/html.md",
      "key": "v-5a38a422",
      "path": "/html/html.html",
      "headers": [
        {
          "level": 2,
          "title": "1.1 前提知识",
          "slug": "_1-1-前提知识"
        },
        {
          "level": 2,
          "title": "1.2 Web标准",
          "slug": "_1-2-web标准"
        },
        {
          "level": 2,
          "title": "2.1 HTML初识",
          "slug": "_2-1-html初识"
        },
        {
          "level": 2,
          "title": "2.2 文档类型声明标签",
          "slug": "_2-2-文档类型声明标签"
        },
        {
          "level": 2,
          "title": "2.3 lang语言种类",
          "slug": "_2-3-lang语言种类"
        },
        {
          "level": 3,
          "title": "2.4 字符集",
          "slug": "_2-4-字符集"
        },
        {
          "level": 2,
          "title": "3.1、标题标签",
          "slug": "_3-1、标题标签"
        },
        {
          "level": 2,
          "title": "3.2、段落标签",
          "slug": "_3-2、段落标签"
        },
        {
          "level": 2,
          "title": "3.3、换行标签/水平线标签",
          "slug": "_3-3、换行标签-水平线标签"
        },
        {
          "level": 2,
          "title": "3.4、文本格式化标签",
          "slug": "_3-4、文本格式化标签"
        },
        {
          "level": 2,
          "title": "3.5 图像标签",
          "slug": "_3-5-图像标签"
        },
        {
          "level": 2,
          "title": "3.6 链接标签(重点)",
          "slug": "_3-6-链接标签-重点"
        },
        {
          "level": 2,
          "title": "3.7 特殊字符",
          "slug": "_3-7-特殊字符"
        },
        {
          "level": 2,
          "title": "4.1 表格标签",
          "slug": "_4-1-表格标签"
        },
        {
          "level": 2,
          "title": "4.2 表格属性",
          "slug": "_4-2-表格属性"
        },
        {
          "level": 2,
          "title": "4.3 列表",
          "slug": "_4-3-列表"
        },
        {
          "level": 2,
          "title": "form表单域",
          "slug": "form表单域"
        },
        {
          "level": 2,
          "title": "input 控件",
          "slug": "input-控件"
        },
        {
          "level": 2,
          "title": "label标签",
          "slug": "label标签"
        },
        {
          "level": 2,
          "title": "textarea控件(文本域)",
          "slug": "textarea控件-文本域"
        },
        {
          "level": 2,
          "title": "select下拉列表",
          "slug": "select下拉列表"
        },
        {
          "level": 2,
          "title": "label的作用是什么？是怎么用的？",
          "slug": "label的作用是什么-是怎么用的"
        },
        {
          "level": 2,
          "title": "什么是 HTML5 的基本构件（building block）？",
          "slug": "什么是-html5-的基本构件-building-block"
        },
        {
          "level": 2,
          "title": "link和@import的区别",
          "slug": "link和-import的区别"
        },
        {
          "level": 2,
          "title": "src与href的区别",
          "slug": "src与href的区别"
        }
      ],
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "6.HTML中的一些细节",
      "frontmatter": {
        "title": "6.HTML中的一些细节",
        "sidebarDepth": 0
      },
      "regularPath": "/html/details.html",
      "relativePath": "html/details.md",
      "key": "v-15ddb0b2",
      "path": "/html/details.html",
      "headers": [
        {
          "level": 3,
          "title": "1、fetch请求",
          "slug": "_1、fetch请求"
        },
        {
          "level": 3,
          "title": "2、xhr请求",
          "slug": "_2、xhr请求"
        },
        {
          "level": 3,
          "title": "3、未跨域报错",
          "slug": "_3、未跨域报错"
        }
      ],
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "11",
      "frontmatter": {},
      "regularPath": "/js/",
      "relativePath": "js/README.md",
      "key": "v-83f098ee",
      "path": "/js/",
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "5.移动端布局",
      "frontmatter": {
        "title": "5.移动端布局",
        "sidebarDepth": 0
      },
      "regularPath": "/html/mobile.html",
      "relativePath": "html/mobile.md",
      "key": "v-07eeab42",
      "path": "/html/mobile.html",
      "headers": [
        {
          "level": 2,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 2,
          "title": "视口",
          "slug": "视口"
        },
        {
          "level": 2,
          "title": "二倍图",
          "slug": "二倍图"
        },
        {
          "level": 2,
          "title": "移动端技术解决方案",
          "slug": "移动端技术解决方案"
        },
        {
          "level": 2,
          "title": "移动端常见布局 - 流失布局",
          "slug": "移动端常见布局-流失布局"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "flex 布局原理 ✍",
          "slug": "flex-布局原理-✍"
        },
        {
          "level": 2,
          "title": "flex 布局父项常见属性",
          "slug": "flex-布局父项常见属性"
        },
        {
          "level": 3,
          "title": "justify-content",
          "slug": "justify-content"
        },
        {
          "level": 3,
          "title": "align-content",
          "slug": "align-content"
        },
        {
          "level": 2,
          "title": "flex 布局子项常见属性",
          "slug": "flex-布局子项常见属性"
        },
        {
          "level": 2,
          "title": "背景线性渐变",
          "slug": "背景线性渐变"
        },
        {
          "level": 2,
          "title": "rem 基础",
          "slug": "rem-基础"
        },
        {
          "level": 2,
          "title": "媒体查询",
          "slug": "媒体查询"
        },
        {
          "level": 3,
          "title": "语法规范",
          "slug": "语法规范"
        },
        {
          "level": 2,
          "title": "Less 基础",
          "slug": "less-基础"
        },
        {
          "level": 3,
          "title": "Less 使用",
          "slug": "less-使用"
        },
        {
          "level": 2,
          "title": "响应式开发",
          "slug": "响应式开发"
        },
        {
          "level": 2,
          "title": "Bootstrap前端开发框",
          "slug": "bootstrap前端开发框"
        },
        {
          "level": 3,
          "title": "Bootstrap 简介",
          "slug": "bootstrap-简介"
        },
        {
          "level": 2,
          "title": "Bootstrap栅格系统",
          "slug": "bootstrap栅格系统"
        }
      ],
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "我是js",
      "frontmatter": {},
      "regularPath": "/js/j1.html",
      "relativePath": "js/j1.md",
      "key": "v-7ce05aa2",
      "path": "/js/j1.html",
      "headers": [
        {
          "level": 2,
          "title": "es6",
          "slug": "es6"
        }
      ],
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    },
    {
      "title": "11",
      "frontmatter": {},
      "regularPath": "/js/j2.html",
      "relativePath": "js/j2.md",
      "key": "v-4f1ec4fc",
      "path": "/js/j2.html",
      "headers": [
        {
          "level": 2,
          "title": "66",
          "slug": "_66"
        }
      ],
      "lastUpdated": "1/5/2022, 5:28:30 PM",
      "lastUpdatedTimestamp": 1641374910000
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.jpg",
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "HTML",
        "link": "/html/html"
      },
      {
        "text": "JS",
        "link": "/js/"
      },
      {
        "text": "AJAX",
        "link": "/ajax/"
      },
      {
        "text": "VUE",
        "link": "/vue/"
      },
      {
        "text": "VUE项目",
        "items": [
          {
            "text": "网抑云音乐PC",
            "link": "http://music.ychzx.top"
          },
          {
            "text": "尚硅谷前台购物项目",
            "link": "http://shop.ychzx.top"
          },
          {
            "text": "黑马后台电商管理项目",
            "link": "http://admin.ychzx.top"
          }
        ]
      }
    ],
    "sidebar": {
      "/html/": [
        "html",
        "css",
        "css2",
        "h5c3",
        "mobile",
        "details"
      ],
      "/js/": [
        "j1",
        "j2"
      ]
    }
  }
}