/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "css": {
      "key": "css",
      "scope": "tags",
      "path": "/tag/css/",
      "pageKeys": [
        "v-0f68e1a2",
        "v-1393ca20"
      ]
    },
    "h5c3新特性": {
      "key": "h5c3新特性",
      "scope": "tags",
      "path": "/tag/h5c3新特性/",
      "pageKeys": [
        "v-66a57ee2"
      ]
    },
    "html": {
      "key": "html",
      "scope": "tags",
      "path": "/tag/html/",
      "pageKeys": [
        "v-5a38a422"
      ]
    },
    "html细节": {
      "key": "html细节",
      "scope": "tags",
      "path": "/tag/html细节/",
      "pageKeys": [
        "v-15ddb0b2"
      ]
    },
    "h5": {
      "key": "h5",
      "scope": "tags",
      "path": "/tag/h5/",
      "pageKeys": [
        "v-07eeab42"
      ]
    }
  },
  "categories": {
    "H5C3": {
      "key": "H5C3",
      "scope": "categories",
      "path": "/categories/H5C3/",
      "pageKeys": [
        "v-0f68e1a2",
        "v-1393ca20",
        "v-66a57ee2",
        "v-5a38a422",
        "v-15ddb0b2"
      ]
    },
    "移动端": {
      "key": "移动端",
      "scope": "categories",
      "path": "/categories/移动端/",
      "pageKeys": [
        "v-07eeab42"
      ]
    }
  },
  "timeline": {}
}