/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "css",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/css/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "视口适配页面",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/视口适配页面/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "h5c3新特性",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/h5c3新特性/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "CSS-查漏补缺",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/CSS-查漏补缺/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "html细节",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/html细节/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "html",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/html/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "h5",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/h5/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "H5C3",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/H5C3/","interval":[0,7]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "移动端",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/移动端/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]